### ISSUE TITLE
PT-05 - Creating UI test framework

### ISSUE THREAD

**Issue by ValBaliyska** [mitko100/Blazor.PennyTracker#10]

**Comment by mitko100** [comment]
Please describe what's your plan. If that task is too big, divide it to subtasks.
Thank you!

**Comment by ValBaliyska** [comment]
This task includes:
- creating the initial structure - folders, classes
- initial initialization of the browser

**Comment by mitko100** [comment]
@ValBaliyska any update on that issue?

**Comment by ValBaliyska** [comment]
> @ValBaliyska any update on that issue?

**Comment by ValBaliyska** [comment]
> > @ValBaliyska any update on that issue?

it's on its way

**Comment by ValBaliyska** [comment]
oops

**Comment by ValBaliyska** [comment]
Done with the skeleton of test automation framework.
