### ISSUE TITLE
PT-21: fix GitHub actions

### ISSUE THREAD

**Issue by mitko100** [mitko100/Blazor.PennyTracker#29]
The test job is failing. The reason for that is executing the automation tests.
Since we do not have a running instance of the application it's impossible to run them. We must create a CD process or remove them from this pipeline.

**Comment by ValBaliyska** [comment]
We can exclude them for now until the app is hosted somewhere.

**Comment by mitko100** [comment]
> We can exclude them for now until the app is hosted somewhere.

I will do that .

**Comment by ValBaliyska** [comment]
> > We can exclude them for now until the app is hosted somewhere.
> 
> I will do that .

Great.
